blog/blog/urls.py
from django.urls import path,reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

app_name="blog"
urlpatterns=[

    path("",views.index,name="index"),
    path("profile/",views.profile,name="profile"),
    path("posts-list/category/<str:category_slug>",views.post_list,name="post_list"),
    path("posts-list/tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path("posts-details/<pk>",views.post_details,name="post_details"),
    path("user-list/",views.user_list,name="user_list"),
    path("user-details/<username>", views.user_details, name="user_details"),
    path("add-post", views.add_post, name="add_post"),
    path("posts-delete/<pk>", views.delete_post, name="delete_post"),
    path("posts-edite/<pk>", views.update_post, name="edite_post"),
    path("delete-image/<pk>", views.delete_image, name="delete_image"),
    path('sign-up/', views.sign_up, name="sign_up"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('password-change/',auth_views.PasswordChangeView.as_view(success_url="done"), name="password-change"),

    path("password-reset/",
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy("blog:password_reset_done")),
         name="password_reset"),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name="password-change-done"),

    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path(
        "password-reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("blog:login")),
        name="password_reset_confirm"
    ),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("post-like/", views.post_like, name="post_like"),
    path("post-save/", views.post_save, name="post_save"),


]

blog/confing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/models.py
from django.db import models
from django.utils import timezone

from django.urls import reverse
from taggit.managers import TaggableManager
from django.template.defaultfilters import slugify
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.

class User(AbstractUser):

    date_of_birth = models.DateField(verbose_name="birth_day", blank=True, null=True)
    bio = models.TextField(verbose_name="bio", null=True, blank=True)
    photo = models.ImageField(verbose_name="image", upload_to="account_images/", blank=True, null=True)
    job = models.CharField(max_length=250, verbose_name="job", null=True, blank=True)
    phone = models.CharField(max_length=11, null=True, blank=True)
    following=models.ManyToManyField("self",related_name="followed",through="UserContact",symmetrical=False)
    # check field name
    def get_absolute_url(self):
        return reverse("blog:user_details", args=[self.username])


class UserImage(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="image")
   image_field = models.ImageField(upload_to="user_image")
   objects = models.Manager()

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)




class Post(models.Model):
    # category
    CATEGORY_CHOICES = (
        ("Culture", "Culture"),
        ("Business", "Business"),
        ("Lifestyle", "Lifestyle"),
        ("Technology", "Technology"),

    )



    #status
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"
        REJECTED = "RJ", "Rejected"

    title=models.CharField(max_length=250)
    meta_description=models.TextField()
    content = models.TextField(default="no description")
    slug=models.CharField(max_length=250)
    id=models.AutoField(primary_key=True)
    category=models.CharField(choices= CATEGORY_CHOICES,default="cul")
    status=models.CharField(choices=Status,default="DF",max_length=2)
    author=models.ForeignKey( settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="posts")
    likes=models.ManyToManyField(User,related_name="liked_post",blank=True)
    saved_by = models.ManyToManyField(User, related_name="saved_post", blank=True)
    # create=models.DateTimeField(auto_now_add=True)
    # update=models.DateTimeField(auto_now=True)
    # publish=models.DateTimeField(timezone.now)
    publish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    #model manager
    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse("blog:post_details",args=[self.id])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        for img in self.images.all():
            path = img.image_field.path
            storage = img.image_field.storage
            storage.delete(path)
        super().delete(*args, **kwargs)


    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"])
        ]
    def __str__(self):
        return self.title


class PostImage(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name="images")
    image_field=models.ImageField(upload_to="post_image")
    # ResizedImageField(size=[2000, 100], crop=['top', 'left'], upload_to='post_image/')
    title = models.CharField(max_length=250,default="image")
    objects = models.Manager()


class UserContact(models.Model):
    user_from=models.ForeignKey(User,related_name="rel_from_set",on_delete=models.CASCADE)
    user_to = models.ForeignKey(User, related_name="rel_to_set", on_delete=models.CASCADE)
    create=models.DateField(auto_now_add=True)
    class meta:
        index=[
            models.Index(fields=["-create"])
        ]
        ordering=("-create")
    def __str__(self):
        return f"{self.user_from} follow {self.user_to}"

blog/blog/forms.py
from django import forms
from .models import *
from taggit.forms import TagWidget

class AddPost(forms.ModelForm):
    image = forms.ImageField(label="image", required=True)

    class Meta:

        model=Post
        fields=["title","meta_description","content","category","tags"]


class RegisterForm(forms.ModelForm):
    image = forms.ImageField(label="image", required=False)
    password1 = forms.CharField(max_length=20, widget=forms.PasswordInput, label="enter password")
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label="repeat password")

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "job", "phone"]

    def clean_password2(self):
        cd = self.cleaned_data
        p1 = cd.get("password1")
        p2 = cd.get("password2")
        if p1 != p2:
            raise forms.ValidationError("Passwords do not match. Please make sure both fields are the same.")
        return p2

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("This phone number is already in use. Please enter a different one.")
        return phone

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken. Please choose another.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email__iexact=email):
            raise forms.ValidationError("This email is already in use. Please enter a different one.")
        return email

blog/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from  django.contrib.auth import authenticate,login,logout
from taggit.models import Tag
from .forms import *
from django.db.models import Count
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

# Create your views here.

def index(request):
    return render(request,"blog/index.html")


# def post_list(request,category=None):
#
#     posts = Post.published.filter(category=category)
#
#
#
#     context={
#         "posts":posts,
#         "category":category,
#
#
#     }
#     return render(request,"blog/post_list.html",context)
#
# def post_list_by_tag(request,tag_slug):
#
#         tag = get_object_or_404(Tag, slug=tag_slug)
#         posts = Post.published.filter(tags__in=[tag])
#
#         context = {
#             "posts": posts,
#         }
#         return render(request, "blog/post_list.html", context)


def post_list(request,category_slug=None,tag_slug=None):

    user=request.user
    posts=Post.published.all()
    category=None
    tag=None
    if category_slug:
        category=category_slug
        posts=Post.published.filter(category=category_slug)

    elif tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        posts=Post.published.filter(tags__in=[tag])

    context = {
        "posts": posts,
        "tag":tag,
        "category":category,
        "user":user
        }
    return render(request, "blog/post_list.html", context)

def user_list(request):
    users=User.objects.all()
    return render(request,"blog/user_list.html",{"users":users})


def post_details(request,pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    tags=post.tags.all()
    post_tags_ids=post.tags.values_list('id',flat=True)
    similar_post=Post.published.filter(tags__in=post_tags_ids).exclude(id=pk)
    similar_post=similar_post.annotate(same_tags=Count('tags')).order_by("-same_tags","create")[:2]
    return render(request,"blog/post_details.html",{"post":post,"tags":tags,"similar_post":similar_post})

def sign_up(request):
    if request.method == "POST":
        form=RegisterForm(request.POST,request.FILES)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data["password2"])
            user.save()
            image = form.cleaned_data.get('image')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password2')
            user = authenticate(request, username=username, password=password)
            login(request, user)
            if form.cleaned_data["image"]:
                UserImage.objects.create(image_field=image, user=user)
            return redirect("blog:profile")
    else:
        form=RegisterForm()
    return render(request,"forms/sign_up.html",{"form":form})


def profile(request):
    user=request.user
    posts=request.user.posts.all()
    return render(request, "blog/profile.html", {"user":user,"posts":posts})


def user_logout(request):
    logout(request)
    return redirect("blog:index")

def add_post(request):
    category = Post.CATEGORY_CHOICES
    if request.method=='POST':
        form=AddPost(request.POST,request.FILES)

        if form.is_valid():
            new_post=form.save(commit=False)
            new_post.author=request.user
            new_post.save()
            form.save_m2m()
            image = form.cleaned_data.get('image')
            if image:
                PostImage.objects.create(image_field=image, post=new_post)

            return redirect("blog:profile")
    else:
        form = AddPost()
    return render(request,"forms/add_post.html",{"form":form,"category":category})


def delete_post(request, pk):
    post=get_object_or_404(Post, id=pk)
    if request.method=="POST":
        post.delete()
        return redirect("blog:profile")

    return render(request,"forms/del_post.html",{"post":post})


def update_post(request, pk):
    post=get_object_or_404(Post, id=pk)
    post_tag=tags_text = ", ".join(tag.name for tag in post.tags.all())

    category = Post.CATEGORY_CHOICES
    if request.method == "POST":
        form = AddPost(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            image = form.cleaned_data.get('image')
            if image:
                PostImage.objects.create(image_field=image, post=post)

            return redirect("blog:profile")
    else:
        form = AddPost(instance=post)

    context = {
        'form': form,
        "post":post,
        "category":category,
        "post_tag":post_tag
    }

    return render(request, "forms/add_post.html", context)

def delete_image(request, pk):
    image = get_object_or_404(PostImage, id=pk)
    image.delete()
    return redirect("blog:add_post")

@login_required
@require_POST
def post_like(request):
    post_id=request.POST.get("post_id")
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        liked = None
        if user in post.likes.all():

            liked=False
            post.likes.remove(user)
        else:
            liked=True
            post.likes.add(user)

        liked_count=post.likes.count()
        response_data={
            "liked":liked,
            "liked_count":liked_count
        }
    else:
        response_data={"error":"post not found"}
    return JsonResponse(response_data)

@login_required
@require_POST
def post_save(request):
    post_id=request.POST.get("post_id")
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        saved = None
        if user in post.saved_by.all():
            saved=False
            post.saved_by.remove(user)
        else:
            saved=True
            post.saved_by.add(user)


        response_data={
            "saved":saved,

        }
    else:
        response_data={"error":"post not found"}
    return JsonResponse(response_data)

def user_details(request,username):
    user = get_object_or_404(User,username=username)
    return render(request,"blog/users_profile.html",{"user":user})

blog/blog/templates/forms/add_post.html
{% extends 'parent/base.html' %}
{% block title %}Create Post{% endblock %}

{% block content %}
<style>
  .create-post-container {
    max-width: 700px;
    margin: 40px auto;
    padding: 30px;
    background-color: #f8f9fa;
    border-radius: 12px;
    box-shadow: 0 0 15px rgba(0, 0, 0, 0.08);
  }

  .post-form p {
    margin-bottom: 15px;
  }

  input[type="text"],
  input[type="file"],
  textarea,
  select {
    width: 100%;
    padding: 10px;
    border: 1px solid #ced4da;
    border-radius: 6px;
    background-color: white;
    font-size: 16px;
  }

  .btn-submit {
    background-color: #007bff;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 6px;
    font-weight: bold;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .btn-submit:hover {
    background-color: #0056b3;
  }

  .images-gallery {
    margin-top: 30px;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 15px;
  }

  .image-item {
    position: relative;
    border: 1px solid #ddd;
    padding: 8px;
    border-radius: 8px;
    background-color: #fff;
  }

  .image-item img {
    max-width: 100%;
    border-radius: 6px;
    display: block;
  }

  .delete-btn {
    position: absolute;
    top: 6px;
    right: 6px;
    background-color: #dc3545;
    color: white;
    padding: 5px 8px;
    font-size: 12px;
    border-radius: 4px;
    text-decoration: none;
    transition: background-color 0.3s;
  }

  .delete-btn:hover {
    background-color: #bd2130;
  }

  .image-count {
    margin-top: 15px;
    font-style: italic;
    color: #555;
    text-align: right;
  }
</style>

<div class="create-post-container">
  <form method="post" enctype="multipart/form-data" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}

   {% if not post.images.all %}
       <p>
            <label for="id_image">Upload new image:</label>
            <input type="file" name="image" id="id_image" class="form-control" />
        </p>
    {% endif %}

    <input type="submit" value="Send" class="btn-submit" />
  </form>

  {% if post.images.all %}
    <div class="images-gallery">
      {% for img in post.images.all %}
        <div class="image-item">
          <img src="{{ img.image_field.url }}" alt="post image" />
          <a href="{% url 'blog:delete_image' img.id %}" class="delete-btn">Delete</a>
        </div>
      {% endfor %}
    </div>
    <p class="image-count">Total images: {{ post.images.count }}</p>
  {% endif %}
</div>
{% endblock %}

blog/blog/templates/forms/del_post.html
{% extends 'parent/base.html' %}
{% block title %}Delete Post{% endblock %}

{% block content %}
<style>
  .delete-post-container {
    background-color: #fff;
    border-radius: 15px;
    padding: 2.5rem;
    max-width: 600px;
    margin: 5rem auto;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
    text-align: center;
  }

  .delete-post-container h2 {
    font-weight: bold;
    color: #dc3545;
    margin-bottom: 1rem;
  }

  .delete-post-container p {
    font-size: 1.1rem;
    margin-bottom: 2rem;
  }

  .btn-delete {
    background-color: #dc3545;
    color: #fff;
    border: none;
    padding: 0.6rem 1.5rem;
    border-radius: 5px;
    margin-right: 1rem;
    transition: background-color 0.3s ease;
  }

  .btn-delete:hover {
    background-color: #c82333;
  }

  .btn-cancel {
    background-color: #6c757d;
    color: #fff;
    padding: 0.6rem 1.5rem;
    border-radius: 5px;
    text-decoration: none;
    transition: background-color 0.3s ease;
  }

  .btn-cancel:hover {
    background-color: #5a6268;
  }
</style>

<div class="delete-post-container">
  <h2><i class="bi bi-trash3-fill me-2"></i>Delete Post</h2>
  <p>Are you sure you want to delete <strong>{{ post.title }}</strong>?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn-delete"><i class="bi bi-x-circle me-1"></i>Delete</button>
    <a href="{{ post.get_absolute_url }}" class="btn-cancel"><i class="bi bi-arrow-left me-1"></i>Cancel</a>
  </form>
</div>
{% endblock %}

blog/blog/templates/forms/sign_up.html
{% extends 'parent/base.html' %}
{% block title %}Sign Up{% endblock %}

{% block content %}

<style>
  .signup-card {
    max-width: 420px;
    width: 100%;
    padding: 2.5rem 2rem;
    border-radius: 1rem;
    box-shadow: 0 12px 25px rgba(13, 110, 253, 0.2);
    background: #fff;
    transition: transform 0.3s ease;
  }
  .signup-card:hover {
    transform: translateY(-8px);
    box-shadow: 0 20px 40px rgba(13, 110, 253, 0.35);
  }
  h2 {
    font-weight: 700;
    color: #0d6efd;
  }
  form .form-control,
  form input,
  form select,
  form textarea {
    width: 100%;
    border-radius: 0.75rem;
    padding: 0.75rem 1rem;
    border: 1.8px solid #ced4da;
    font-size: 1rem;
    transition: border-color 0.3s ease, box-shadow 0.3s ease;
    box-sizing: border-box;
  }
  form .form-control:focus,
  form input:focus,
  form select:focus,
  form textarea:focus {
    border-color: #0d6efd;
    box-shadow: 0 0 8px rgba(13, 110, 253, 0.5);
    outline: none;
  }
  form p {
    margin-bottom: 1rem;
  }
  form label {
    font-weight: 600;
    margin-bottom: 0.3rem;
    display: block;
    color: #212529;
  }
  button.btn-success {
    border-radius: 2rem;
    padding: 0.75rem 1.5rem;
    font-weight: 600;
    letter-spacing: 0.05em;
    transition: background-color 0.3s ease, box-shadow 0.3s ease;
  }
  button.btn-success:hover {
    background-color: #0b5ed7;
    box-shadow: 0 8px 16px rgba(11, 94, 215, 0.5);
  }
  .alert {
    border-radius: 0.75rem;
  }
</style>

<div class="container d-flex justify-content-center align-items-center min-vh-100">
  <div class="signup-card shadow-sm">
    <h2 class="text-center mb-3">Create Your Account 🎉</h2>
    <p class="text-center text-muted mb-4">Please fill the form to sign up</p>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {{ form.as_p }}

      <div class="d-grid mt-4">
        <button type="submit" class="btn btn-success">Sign Up</button>
      </div>

      {% if form.errors %}
      <div class="alert alert-danger mt-4" role="alert">
        please cheek errors.
      </div>
      {% endif %}
    </form>
  </div>
</div>

{% endblock %}