blog/blog/urls.py
from django.urls import path,reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

app_name="blog"
urlpatterns=[

    path("",views.index,name="index"),
    path("profile/",views.profile,name="profile"),
    path("posts-list/category/<str:category_slug>",views.post_list,name="post_list"),
    path("posts-list/tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path("posts-details/<pk>",views.post_details,name="post_details"),
    path("user-list/",views.user_list,name="user_list"),
    path("user-details/<username>", views.user_details, name="user_details"),
    path("add-post", views.add_post, name="add_post"),
    path("posts-delete/<pk>", views.delete_post, name="delete_post"),
    path("posts-edite/<pk>", views.update_post, name="edite_post"),
    path("delete-image/<pk>", views.delete_image, name="delete_image"),
    path('sign-up/', views.sign_up, name="sign_up"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('password-change/',auth_views.PasswordChangeView.as_view(success_url="done"), name="password-change"),

    path("password-reset/",
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy("blog:password_reset_done")),
         name="password_reset"),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name="password-change-done"),

    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path(
        "password-reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("blog:login")),
        name="password_reset_confirm"
    ),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("post-like/", views.post_like, name="post_like"),
    path("post-save/", views.post_save, name="post_save"),


]

blog/confing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/models.py
from django.db import models
from django.utils import timezone

from django.urls import reverse
from taggit.managers import TaggableManager
from django.template.defaultfilters import slugify
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.

class User(AbstractUser):

    date_of_birth = models.DateField(verbose_name="birth_day", blank=True, null=True)
    bio = models.TextField(verbose_name="bio", null=True, blank=True)
    photo = models.ImageField(verbose_name="image", upload_to="account_images/", blank=True, null=True)
    job = models.CharField(max_length=250, verbose_name="job", null=True, blank=True)
    phone = models.CharField(max_length=11, null=True, blank=True)
    following=models.ManyToManyField("self",related_name="followed",through="UserContact",symmetrical=False)
    # check field name
    def get_absolute_url(self):
        return reverse("blog:user_details", args=[self.username])


class UserImage(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="image")
   image_field = models.ImageField(upload_to="user_image")
   objects = models.Manager()

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)




class Post(models.Model):
    # category
    CATEGORY_CHOICES = (
        ("Culture", "Culture"),
        ("Business", "Business"),
        ("Lifestyle", "Lifestyle"),
        ("Technology", "Technology"),

    )



    #status
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"
        REJECTED = "RJ", "Rejected"

    title=models.CharField(max_length=250)
    meta_description=models.TextField()
    content = models.TextField(default="no description")
    slug=models.CharField(max_length=250)
    id=models.AutoField(primary_key=True)
    category=models.CharField(choices= CATEGORY_CHOICES,default="cul")
    status=models.CharField(choices=Status,default="DF",max_length=2)
    author=models.ForeignKey( settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="posts")
    likes=models.ManyToManyField(User,related_name="liked_post",blank=True)
    saved_by = models.ManyToManyField(User, related_name="saved_post", blank=True)
    # create=models.DateTimeField(auto_now_add=True)
    # update=models.DateTimeField(auto_now=True)
    # publish=models.DateTimeField(timezone.now)
    publish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    #model manager
    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse("blog:post_details",args=[self.id])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        for img in self.images.all():
            path = img.image_field.path
            storage = img.image_field.storage
            storage.delete(path)
        super().delete(*args, **kwargs)


    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"])
        ]
    def __str__(self):
        return self.title


class PostImage(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name="images")
    image_field=models.ImageField(upload_to="post_image")
    # ResizedImageField(size=[2000, 100], crop=['top', 'left'], upload_to='post_image/')
    title = models.CharField(max_length=250,default="image")
    objects = models.Manager()


class UserContact(models.Model):
    user_from=models.ForeignKey(User,related_name="rel_from_set",on_delete=models.CASCADE)
    user_to = models.ForeignKey(User, related_name="rel_to_set", on_delete=models.CASCADE)
    create=models.DateField(auto_now_add=True)
    class meta:
        index=[
            models.Index(fields=["-create"])
        ]
        ordering=("-create")
    def __str__(self):
        return f"{self.user_from} follow {self.user_to}"

blog/blog/forms.py
from django import forms
from .models import *
from taggit.forms import TagWidget

class AddPost(forms.ModelForm):
    image = forms.ImageField(label="image", required=True)

    class Meta:

        model=Post
        fields=["title","meta_description","content","category","tags"]


class RegisterForm(forms.ModelForm):
    image = forms.ImageField(label="image", required=False)
    password1 = forms.CharField(max_length=20, widget=forms.PasswordInput, label="enter password")
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label="repeat password")

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "job", "phone"]

    def clean_password2(self):
        cd = self.cleaned_data
        p1 = cd.get("password1")
        p2 = cd.get("password2")
        if p1 != p2:
            raise forms.ValidationError("Passwords do not match. Please make sure both fields are the same.")
        return p2

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("This phone number is already in use. Please enter a different one.")
        return phone

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken. Please choose another.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email__iexact=email):
            raise forms.ValidationError("This email is already in use. Please enter a different one.")
        return email

blog/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from  django.contrib.auth import authenticate,login,logout
from taggit.models import Tag
from .forms import *
from django.db.models import Count
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

# Create your views here.

def index(request):
    return render(request,"blog/index.html")


# def post_list(request,category=None):
#
#     posts = Post.published.filter(category=category)
#
#
#
#     context={
#         "posts":posts,
#         "category":category,
#
#
#     }
#     return render(request,"blog/post_list.html",context)
#
# def post_list_by_tag(request,tag_slug):
#
#         tag = get_object_or_404(Tag, slug=tag_slug)
#         posts = Post.published.filter(tags__in=[tag])
#
#         context = {
#             "posts": posts,
#         }
#         return render(request, "blog/post_list.html", context)


def post_list(request,category_slug=None,tag_slug=None):

    user=request.user
    posts=Post.published.all()
    category=None
    tag=None
    if category_slug:
        category=category_slug
        posts=Post.published.filter(category=category_slug)

    elif tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        posts=Post.published.filter(tags__in=[tag])

    context = {
        "posts": posts,
        "tag":tag,
        "category":category,
        "user":user
        }
    return render(request, "blog/post_list.html", context)

def user_list(request):
    users=User.objects.all()
    return render(request,"blog/user_list.html",{"users":users})


def post_details(request,pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    tags=post.tags.all()
    post_tags_ids=post.tags.values_list('id',flat=True)
    similar_post=Post.published.filter(tags__in=post_tags_ids).exclude(id=pk)
    similar_post=similar_post.annotate(same_tags=Count('tags')).order_by("-same_tags","create")[:2]
    return render(request,"blog/post_details.html",{"post":post,"tags":tags,"similar_post":similar_post})

def sign_up(request):
    if request.method == "POST":
        form=RegisterForm(request.POST,request.FILES)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data["password2"])
            user.save()
            image = form.cleaned_data.get('image')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password2')
            user = authenticate(request, username=username, password=password)
            login(request, user)
            if form.cleaned_data["image"]:
                UserImage.objects.create(image_field=image, user=user)
            return redirect("blog:profile")
    else:
        form=RegisterForm()
    return render(request,"forms/sign_up.html",{"form":form})


def profile(request):
    user=request.user
    posts=request.user.posts.all()
    return render(request, "blog/profile.html", {"user":user,"posts":posts})


def user_logout(request):
    logout(request)
    return redirect("blog:index")

def add_post(request):
    category = Post.CATEGORY_CHOICES
    if request.method=='POST':
        form=AddPost(request.POST,request.FILES)

        if form.is_valid():
            new_post=form.save(commit=False)
            new_post.author=request.user
            new_post.save()
            form.save_m2m()
            image = form.cleaned_data.get('image')
            if image:
                PostImage.objects.create(image_field=image, post=new_post)

            return redirect("blog:profile")
    else:
        form = AddPost()
    return render(request,"forms/add_post.html",{"form":form,"category":category})


def delete_post(request, pk):
    post=get_object_or_404(Post, id=pk)
    if request.method=="POST":
        post.delete()
        return redirect("blog:profile")

    return render(request,"forms/del_post.html",{"post":post})


def update_post(request, pk):
    post=get_object_or_404(Post, id=pk)
    post_tag=tags_text = ", ".join(tag.name for tag in post.tags.all())

    category = Post.CATEGORY_CHOICES
    if request.method == "POST":
        form = AddPost(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            image = form.cleaned_data.get('image')
            if image:
                PostImage.objects.create(image_field=image, post=post)

            return redirect("blog:profile")
    else:
        form = AddPost(instance=post)

    context = {
        'form': form,
        "post":post,
        "category":category,
        "post_tag":post_tag
    }

    return render(request, "forms/add_post.html", context)

def delete_image(request, pk):
    image = get_object_or_404(PostImage, id=pk)
    image.delete()
    return redirect("blog:add_post")

@login_required
@require_POST
def post_like(request):
    post_id=request.POST.get("post_id")
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        liked = None
        if user in post.likes.all():

            liked=False
            post.likes.remove(user)
        else:
            liked=True
            post.likes.add(user)

        liked_count=post.likes.count()
        response_data={
            "liked":liked,
            "liked_count":liked_count
        }
    else:
        response_data={"error":"post not found"}
    return JsonResponse(response_data)

@login_required
@require_POST
def post_save(request):
    post_id=request.POST.get("post_id")
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        saved = None
        if user in post.saved_by.all():
            saved=False
            post.saved_by.remove(user)
        else:
            saved=True
            post.saved_by.add(user)


        response_data={
            "saved":saved,

        }
    else:
        response_data={"error":"post not found"}
    return JsonResponse(response_data)

def user_details(request,username):
    user = get_object_or_404(User,username=username)
    return render(request,"blog/users_profile.html",{"user":user})

blog/blog/templates/blog/index.html
<!-- main_content.html -->
{% extends 'parent/base.html' %}

{% block title %}Blog{% endblock %}

{% block content %}

<!-- Culture Category Section (Simple Version without Images) -->
<!--<section id="business-category" class="business-category section py-5">-->
<!--  <div class="container" data-aos="fade-up">-->

<!--    &lt;!&ndash; عنوان بخش &ndash;&gt;-->
<!--    <div class="d-flex justify-content-between align-items-center mb-4">-->
<!--      <h2 class="mb-0">Business</h2>-->
<!--      <a href="categories.html" class="text-decoration-none">See All Business</a>-->
<!--    </div>-->

<!--    &lt;!&ndash; ردیف پست‌ها &ndash;&gt;-->
<!--    <div class="row g-4" data-aos="fade-up" data-aos-delay="100">-->

<!--      &lt;!&ndash; یک کارت پست &ndash;&gt;-->
<!--      <div class="col-lg-4 col-md-6">-->
<!--        <div class="card h-100 shadow-sm border-0">-->
<!--          <img src="assets/img/post-landscape-3.jpg" class="card-img-top" alt="...">-->
<!--          <div class="card-body d-flex flex-column justify-content-between">-->
<!--            <div>-->
<!--              <div class="text-muted small mb-2">-->
<!--                <span class="badge bg-primary">Business</span> • Jul 5th '22-->
<!--              </div>-->
<!--              <h5 class="card-title">-->
<!--                <a href="blog-details.html" class="text-dark text-decoration-none">-->
<!--                  What is the son of Football Coach John Gruden doing now?-->
<!--                </a>-->
<!--              </h5>-->
<!--              <p class="card-text small">-->
<!--                Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio placeat magni...-->
<!--              </p>-->
<!--            </div>-->
<!--            <div class="d-flex align-items-center mt-3">-->
<!--              <img src="assets/img/person-4.jpg" alt="Author" class="rounded-circle me-2" width="40" height="40">-->
<!--              <small class="text-muted">Wade Warren</small>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->

<!--      &lt;!&ndash; کپی کن و پست‌های دیگه اضافه کن &ndash;&gt;-->
<!--      <div class="col-lg-4 col-md-6">-->
<!--        <div class="card h-100 shadow-sm border-0">-->
<!--          <img src="assets/img/post-landscape-5.jpg" class="card-img-top" alt="...">-->
<!--          <div class="card-body d-flex flex-column justify-content-between">-->
<!--            <div>-->
<!--              <div class="text-muted small mb-2">-->
<!--                <span class="badge bg-primary">Business</span> • Jul 5th '22-->
<!--              </div>-->
<!--              <h5 class="card-title">-->
<!--                <a href="blog-details.html" class="text-dark text-decoration-none">-->
<!--                  11 Work From Home Part-Time Jobs You Can Do Now-->
<!--                </a>-->
<!--              </h5>-->
<!--              <p class="card-text small">-->
<!--                Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio placeat magni...-->
<!--              </p>-->
<!--            </div>-->
<!--            <div class="d-flex align-items-center mt-3">-->
<!--              <img src="assets/img/person-1.jpg" alt="Author" class="rounded-circle me-2" width="40" height="40">-->
<!--              <small class="text-muted">Jenny Wilson</small>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->

<!--      &lt;!&ndash; همین کارت رو برای همه پست‌ها استفاده کن &ndash;&gt;-->
<!--      &lt;!&ndash; ادامه... &ndash;&gt;-->
<!--    </div>-->
<!--  </div>-->
<!--</section>-->
<section  class="post-category section py-5">
  <div class="container" data-aos="fade-up">

    <!-- عنوان دسته -->
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h2 class="mb-0">Business</h2>
      <a href="categories/business.html" class="text-decoration-none">See All Business</a>
    </div>

    <!-- پست‌های دسته -->
    <div class="row g-4" data-aos="fade-up" data-aos-delay="100">

      <!-- یک کارت پست -->
      <div class="col-lg-4 col-md-6">
        <div class="card h-100 shadow-sm border-0">
          <img src="assets/img/post-business-1.jpg" class="card-img-top" alt="Business Post">
          <div class="card-body d-flex flex-column justify-content-between">
            <div>
              <div class="text-muted small mb-2">
                <span class="badge bg-primary">Business</span> • Jul 5th '22
              </div>
              <h5 class="card-title">
                <a href="blog-details.html" class="text-dark text-decoration-none">
                  Title of Business Post
                </a>
              </h5>
              <p class="card-text small">
                Brief description of the business post goes here...
              </p>
            </div>
            <div class="d-flex align-items-center mt-3">
              <img src="assets/img/person-1.jpg" alt="Author" class="rounded-circle me-2" width="40" height="40">
              <small class="text-muted">Author Name</small>
            </div>
          </div>
        </div>
      </div>

      <!-- کارت‌های دیگه همینجا اضافه کن -->
    </div>
  </div>
</section>



{% endblock %}

blog/blog/templates/blog/post_list.html
<!-- main_content.html -->
{% extends 'parent/base.html' %}

{% block title %}{{category}}{% endblock %}

{% block content %}

<section  class="post-category section py-5">
  <div class="container" data-aos="fade-up">

    <!-- عنوان دسته -->
    <div class="d-flex justify-content-between align-items-center mb-4">
      {% if category %}
          <h2 class="mb-0">{{category}}</h2>
      {% else %}
        <h2 class="mb-0">{{tag}}</h2>
      {% endif %}

    </div>

    <!-- پست‌های دسته -->
    <div class="row g-4" data-aos="fade-up" data-aos-delay="100">

      <!-- یک کارت پست -->

      {% for post in posts %}
        <div class="col-lg-4 col-md-6">
        <div class="card h-100 shadow-sm border-0">
          <div class="ratio ratio-16x9 rounded overflow-hidden">
              <img src="{{ post.images.first.image_field.url }}" class="w-100 h-100 object-fit-cover" alt="Business Post">
          </div>


          <div class="card-body d-flex flex-column justify-content-between">
            <div>
              <div class="text-muted small mb-2">
                <span class="badge bg-primary">{{post.category}}</span> • {{post.create}}
              </div>
              <h5 class="card-title">
                <a href="{{ post.get_absolute_url }}" class="text-dark text-decoration-none">
                  {{post.title}}
                </a>
              </h5>
              <p class="card-text small">
                {{post.meta_description}}
              </p>
            </div>
            <div class="d-flex align-items-center mt-3">
              <a href="{{ post.author.get_absolute_url }}">
                <img src="{{ post.author.image.first.image_field.url }}" alt="Author" class="rounded-circle me-2" width="40" height="40">
              </a>
              <small class="text-muted">{{post.author}}</small>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
        <p>category is null</p>
      {% endfor %}

      <!-- کارت‌های دیگه همینجا اضافه کن -->
    </div>
  </div>
</section>



{% endblock %}

blog/blog/templates/blog/profile.html
{% extends 'parent/base.html' %}

{% block title %}User Profile{% endblock %}

{% block content %}
<style>
  .profile-container {
    background-color: #fff;
    border-radius: 15px;
    padding: 2rem;
    box-shadow: 0 4px 12px rgba(0,0,0,0.08);
  }

  .profile-pic {
    width: 130px;
    height: 130px;
    border-radius: 50%;
    object-fit: cover;
    border: 4px solid #0d6efd;
    box-shadow: 0 0 10px rgba(13, 110, 253, 0.3);
  }

  .nav-tabs .nav-link.active {
    background-color: #0d6efd;
    color: #fff !important;
    border-radius: 10px;
  }

  .post-card {
    border-radius: 10px;
    padding: 1.5rem;
    margin-bottom: 1rem;
    background-color: #f8f9fa;
    transition: all 0.2s ease-in-out;
  }

  .post-card:hover {
    background-color: #e9ecef;
  }

  .settings-btn {
    text-align: left;
    padding: 0.75rem 1rem;
    font-size: 1rem;
    border-radius: 10px;
  }

  .form-control:focus {
    box-shadow: none;
    border-color: #0d6efd;
  }
</style>

<div class="container my-5">
  <div class="profile-container text-center mb-5">
    <img src="{{ user.image.first.image_field.url }}" alt="User" class="profile-pic mb-3 h-20 w-20">
    <h3 class="fw-bold mb-1">{{ user.username }}</h3>
    <p class="text-muted mb-1">{{ user.bio|default:"No biography provided." }}</p>
    <p class="text-muted mb-0">Date of birth: {{ user.date_of_birth|default:"N/A" }}</p>
  </div>

  <ul class="nav nav-tabs justify-content-center mb-4" id="profile-tabs" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="posts-tab" data-bs-toggle="tab" data-bs-target="#posts" type="button" role="tab">📝 Posts</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="settings-tab" data-bs-toggle="tab" data-bs-target="#settings" type="button" role="tab">⚙️ Settings</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="edit-profile-tab" data-bs-toggle="tab" data-bs-target="#edit-profile" type="button" role="tab">✏️ Edit Profile</button>
    </li>
  </ul>

  <div class="tab-content">

    <!-- Posts Section -->
    <div class="tab-pane fade show active" id="posts" role="tabpanel">
      {% if posts %}
        {% for post in posts %}
          <div class="post-card">
            <h5 class="fw-bold mb-2">{{ post.title }}</h5>
            <p class="text-muted">{{ post.meta_description|truncatechars:150 }}</p>
            <div class="text-end">
              <a href="{% url 'blog:delete_post' post.pk %}" class="btn btn-sm btn-outline-danger">
                <i class="bi bi-trash"></i> Delete
              </a>
              <a href="{% url 'blog:edite_post' post.pk %}" class="btn btn-sm btn-outline-primary">
                <i class="bi bi-pencil-square"></i> Edit
              </a>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="alert alert-info text-center">No posts yet.</div>
      {% endif %}
    </div>

    <!-- Settings Section -->
    <div class="tab-pane fade" id="settings" role="tabpanel">
      <div class="d-grid gap-3 mt-3 col-md-6 mx-auto">
        <a href="{% url 'blog:add_post' %}" class="btn btn-primary settings-btn">
          <i class="bi bi-pencil-square me-2"></i> Add New Post
        </a>
        <a href="{% url 'blog:password-change' %}" class="btn btn-warning settings-btn">
          <i class="bi bi-key me-2"></i> Change Password
        </a>
        <a href="{% url 'blog:logout' %}" class="btn btn-secondary settings-btn">
          <i class="bi bi-box-arrow-right me-2"></i> Logout
        </a>
      </div>
    </div>

    <!-- Edit Profile Section -->
    <div class="tab-pane fade" id="edit-profile" role="tabpanel">
      <form method="POST" action="#" class="col-md-8 mx-auto mt-4">
        {% csrf_token %}
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}">
        </div>
        <div class="mb-3">
          <label for="bio" class="form-label">Bio</label>
          <textarea class="form-control" id="bio" name="bio" rows="3">{{ user.bio }}</textarea>
        </div>
        <div class="mb-3">
          <label for="birthday" class="form-label">Date of Birth</label>
          <input type="date" class="form-control" id="birthday" name="birthday" value="{{ user.date_of_birth|date:'Y-m-d' }}">
        </div>
        <div class="text-end">
          <button type="submit" class="btn btn-success">
            <i class="bi bi-check-circle"></i> Save Changes
          </button>
        </div>
      </form>
    </div>

  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

blog/blog/templates/blog/user_list.html
{% extends 'parent/base.html' %}

{% block title %}Users List{% endblock %}

{% block content %}
<style>
    .user-card {
      background-color: #fff;
      border-radius: 15px;
      padding: 1.5rem;
      box-shadow: 0 4px 12px rgba(0,0,0,0.08);
      text-align: center;
      transition: transform 0.2s ease-in-out;
    }

    .user-card:hover {
      transform: translateY(-3px);
    }

    .user-pic {
      width: 90px;
      height: 90px;
      border-radius: 50%;
      object-fit: cover;
      border: 3px solid #0d6efd;
      box-shadow: 0 0 8px rgba(13, 110, 253, 0.3);
      margin-bottom: 0.8rem;
    }

    .user-name {
      font-weight: bold;
      font-size: 1.1rem;
    }

    .user-bio {
      font-size: 0.9rem;
      color: #6c757d;
      min-height: 40px;
    }

    .stats {
      display: flex;
      justify-content: center;
      gap: 1rem;
      margin: 0.8rem 0;
    }

    .stats-item h6 {
      margin: 0;
      font-weight: bold;
    }

    .stats-item p {
      margin: 0;
      font-size: 0.8rem;
      color: #6c757d;
    }

    @media (max-width: 576px) {
      .stats {
        flex-direction: column;
        gap: 0.5rem;
      }
    }
</style>

<div class="container my-5">
    <h2 class="fw-bold mb-4 text-center">Users</h2>
    <div class="row g-4">
        {% for u in users %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="user-card">
                <a href="{{ u.get_absolute_url }}">
                    <img src="{{ u.image.first.image_field.url }}" alt="{{ u.username }}" class="user-pic">
                    <div class="user-name">{{ u.username }}</div>
                </a>

                <p class="user-bio">{{ u.bio|default:"No biography provided." }}</p>

                <div class="stats">
                    <div class="stats-item">
                        <h6>{{ u.followers_count }}</h6>
                        <p>Followers</p>
                    </div>
                    <div class="stats-item">
                        <h6>{{ u.following_count }}</h6>
                        <p>Following</p>
                    </div>
                </div>

                {% if u.is_following %}
                <button class="btn btn-outline-danger btn-sm">
                    <i class="bi bi-person-dash"></i> Unfollow
                </button>
                {% else %}
                <button class="btn btn-primary btn-sm">
                    <i class="bi bi-person-plus"></i> Follow
                </button>
                {% endif %}
            </div>
        </div>

        {% endfor %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}